import type { NextPage } from "next";
import Head from "next/head";
import { Table } from "../components/Table";
import styles from "../styles/Home.module.css";
import { GetStaticProps } from "next";
import { prisma } from "../utils/db";

interface TableProps {
  links: string[];
}

const Home: NextPage<TableProps> = ({ links }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Payme shop list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.body}>
        <Table links={links} />
      </main>
    </div>
  );
};

export default Home;

export async function getStaticProps() {
  // const readLinks = async () => {
  //   await prisma.links.findMany();
  // };
  const links = await prisma.links.findMany();
  return {
    props: {
      links: JSON.parse(JSON.stringify(links)),
    },
  };
}
